// Code generated by protoc-gen-twirplura v1.0.0, DO NOT EDIT.
// source: protos/number-service/service.proto

package number

import context "context"
import json "encoding/json"
import fmt "fmt"

import "github.com/kyawmyintthein/lura-twirp"
import "github.com/luraproject/lura/config"
import "github.com/luraproject/lura/logging"
import twirp "github.com/twitchtv/twirp"
import proto "google.golang.org/protobuf/proto"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =========================
// NumberService Lura Client
// =========================

type numberServiceLuraClient struct {
	id      string
	service NumberService
	l       logging.Logger
}

// =====================
// NumberService Methods
// =====================

const (
	_NumberServiceMethod_Add = "Add"
)

// =================================================================================================
// NewNumberServiceLuraClient creates a Protobuf client that implements the NumberService interface.
// =================================================================================================

func NewNumberServiceLuraClient(config *config.ServiceConfig, id string, client HTTPClient, l logging.Logger, opts ...twirp.ClientOption) (luratwirp.LuraTwirpStub, error) {
	baseURL, err := getBaseURLByNumberServiceClientID(config, id)
	if err != nil {
		return nil, err
	}
	protobufClient := NewNumberServiceProtobufClient(baseURL, client, opts...)
	return &numberServiceLuraClient{
		id:      id,
		service: protobufClient,
		l:       l,
	}, nil
}

// ==================================
// NumberService getBaseURLByClientID
// ==================================

func getBaseURLByNumberServiceClientID(config *config.ServiceConfig, id string) (string, error) {
	for _, endpoint := range config.Endpoints {
		val, ok := endpoint.ExtraConfig[luratwirp.TwirpServiceIdentifierConst].(string)
		if ok {
			if val != id {
				continue
			}
			for _, backend := range endpoint.Backend {
				_, ok := backend.ExtraConfig[luratwirp.TwirpServiceIdentifierConst].(string)
				if ok {
					if val != id {
						continue
					}
					if len(backend.Host) <= 0 {
						return "", twirp.InternalError("invalid host configuration")
					}
				}
				return backend.Host[0], nil
			}
		}
	}
	return "", twirp.InternalError(fmt.Sprintf("invalid %s", luratwirp.TwirpServiceIdentifierConst))
}

// ==============================================================
// Invoke invoke RPC function regarding given service and method.
// ==============================================================

func (c *numberServiceLuraClient) Invoke(ctx context.Context, service string, method string, in proto.Message) (proto.Message, error) {
	switch method {
	case _NumberServiceMethod_Add:
		req, ok := in.(*AddNumberRequest)
		if !ok {
			return nil, twirp.InternalError("invalid protobuf message")
		}
		resp, err := c.service.Add(ctx, req)
		if err != nil {
			c.l.Error(err, "failed to invoke : ", _NumberServiceMethod_Add)
			return resp, err
		}
		return resp, err
	}
	return nil, twirp.InternalError(fmt.Sprintf("invalid %s", luratwirp.TwirpServiceIdentifierConst))
}

// ===================================================================
// Identifier return client identifier to lura-twirp backend registery
// ===================================================================

func (c *numberServiceLuraClient) Identifier() string {
	return c.id
}

// ====================================
// Encode convert JSON to proto.Message
// ====================================

func (c *numberServiceLuraClient) Encode(ctx context.Context, method string, data []byte) (proto.Message, error) {
	switch method {
	case _NumberServiceMethod_Add:
		out := new(AddNumberRequest)
		err := json.Unmarshal(data, out)
		if err != nil {
			c.l.Error(err, "failed to unmarhsal : ", _NumberServiceMethod_Add)
			return out, err
		}
		return out, err
	}
	return nil, twirp.InternalError(fmt.Sprintf("invalid method %s", method))
}

// ====================================
// Decode convert proto.Message to JSON
// ====================================

func (c *numberServiceLuraClient) Decode(ctx context.Context, method string, msg proto.Message) ([]byte, error) {
	switch method {
	case _NumberServiceMethod_Add:
		out, err := proto.Marshal(msg)
		if err != nil {
			c.l.Error(err, "failed to marshal : ", _NumberServiceMethod_Add)
			return out, err
		}
		return out, err
	}
	return nil, twirp.InternalError(fmt.Sprintf("invalid method %s", method))
}
