// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protos/number-service/service.proto

package number

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *AddNumberRequest) Reset() {
	*x = AddNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_number_service_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNumberRequest) ProtoMessage() {}

func (x *AddNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_number_service_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNumberRequest.ProtoReflect.Descriptor instead.
func (*AddNumberRequest) Descriptor() ([]byte, []int) {
	return file_protos_number_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddNumberRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddNumberRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddResultResponse) Reset() {
	*x = AddResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_number_service_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResultResponse) ProtoMessage() {}

func (x *AddResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_number_service_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResultResponse.ProtoReflect.Descriptor instead.
func (*AddResultResponse) Descriptor() ([]byte, []int) {
	return file_protos_number_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddResultResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_protos_number_service_service_proto protoreflect.FileDescriptor

var file_protos_number_service_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x2e, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x62, 0x22, 0x2b, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x53,
	0x0a, 0x0d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x42, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x1c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_number_service_service_proto_rawDescOnce sync.Once
	file_protos_number_service_service_proto_rawDescData = file_protos_number_service_service_proto_rawDesc
)

func file_protos_number_service_service_proto_rawDescGZIP() []byte {
	file_protos_number_service_service_proto_rawDescOnce.Do(func() {
		file_protos_number_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_number_service_service_proto_rawDescData)
	})
	return file_protos_number_service_service_proto_rawDescData
}

var file_protos_number_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_number_service_service_proto_goTypes = []interface{}{
	(*AddNumberRequest)(nil),  // 0: rpc.number.AddNumberRequest
	(*AddResultResponse)(nil), // 1: rpc.number.AddResultResponse
}
var file_protos_number_service_service_proto_depIdxs = []int32{
	0, // 0: rpc.number.NumberService.Add:input_type -> rpc.number.AddNumberRequest
	1, // 1: rpc.number.NumberService.Add:output_type -> rpc.number.AddResultResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_number_service_service_proto_init() }
func file_protos_number_service_service_proto_init() {
	if File_protos_number_service_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_number_service_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_number_service_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_number_service_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_number_service_service_proto_goTypes,
		DependencyIndexes: file_protos_number_service_service_proto_depIdxs,
		MessageInfos:      file_protos_number_service_service_proto_msgTypes,
	}.Build()
	File_protos_number_service_service_proto = out.File
	file_protos_number_service_service_proto_rawDesc = nil
	file_protos_number_service_service_proto_goTypes = nil
	file_protos_number_service_service_proto_depIdxs = nil
}
