// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protos/color-service/service.proto

package color

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetRandomColorRequest) Reset() {
	*x = GetRandomColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_color_service_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomColorRequest) ProtoMessage() {}

func (x *GetRandomColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_color_service_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomColorRequest.ProtoReflect.Descriptor instead.
func (*GetRandomColorRequest) Descriptor() ([]byte, []int) {
	return file_protos_color_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomColorRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRandomColorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colors []string `protobuf:"bytes,1,rep,name=colors,proto3" json:"colors,omitempty"`
}

func (x *GetRandomColorResp) Reset() {
	*x = GetRandomColorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_color_service_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomColorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomColorResp) ProtoMessage() {}

func (x *GetRandomColorResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_color_service_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomColorResp.ProtoReflect.Descriptor instead.
func (*GetRandomColorResp) Descriptor() ([]byte, []int) {
	return file_protos_color_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomColorResp) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

type GetRGBColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRGBColorRequest) Reset() {
	*x = GetRGBColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_color_service_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRGBColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRGBColorRequest) ProtoMessage() {}

func (x *GetRGBColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_color_service_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRGBColorRequest.ProtoReflect.Descriptor instead.
func (*GetRGBColorRequest) Descriptor() ([]byte, []int) {
	return file_protos_color_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetRGBColorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRGBColorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Red   int64 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green int64 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue  int64 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
}

func (x *GetRGBColorResp) Reset() {
	*x = GetRGBColorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_color_service_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRGBColorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRGBColorResp) ProtoMessage() {}

func (x *GetRGBColorResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_color_service_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRGBColorResp.ProtoReflect.Descriptor instead.
func (*GetRGBColorResp) Descriptor() ([]byte, []int) {
	return file_protos_color_service_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetRGBColorResp) GetRed() int64 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *GetRGBColorResp) GetGreen() int64 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *GetRGBColorResp) GetBlue() int64 {
	if x != nil {
		return x.Blue
	}
	return 0
}

var File_protos_color_service_service_proto protoreflect.FileDescriptor

var file_protos_color_service_service_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22,
	0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2c,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x22, 0x28, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x52, 0x47, 0x42, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x47, 0x42,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x72, 0x65, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67, 0x72, 0x65, 0x65,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x62, 0x6c, 0x75, 0x65, 0x32, 0xab, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x52, 0x47, 0x42, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x47, 0x42, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x47, 0x42, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_color_service_service_proto_rawDescOnce sync.Once
	file_protos_color_service_service_proto_rawDescData = file_protos_color_service_service_proto_rawDesc
)

func file_protos_color_service_service_proto_rawDescGZIP() []byte {
	file_protos_color_service_service_proto_rawDescOnce.Do(func() {
		file_protos_color_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_color_service_service_proto_rawDescData)
	})
	return file_protos_color_service_service_proto_rawDescData
}

var file_protos_color_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_color_service_service_proto_goTypes = []interface{}{
	(*GetRandomColorRequest)(nil), // 0: rpc.color.GetRandomColorRequest
	(*GetRandomColorResp)(nil),    // 1: rpc.color.GetRandomColorResp
	(*GetRGBColorRequest)(nil),    // 2: rpc.color.GetRGBColorRequest
	(*GetRGBColorResp)(nil),       // 3: rpc.color.GetRGBColorResp
}
var file_protos_color_service_service_proto_depIdxs = []int32{
	0, // 0: rpc.color.ColorService.GetRandomColor:input_type -> rpc.color.GetRandomColorRequest
	2, // 1: rpc.color.ColorService.GetRGBColor:input_type -> rpc.color.GetRGBColorRequest
	1, // 2: rpc.color.ColorService.GetRandomColor:output_type -> rpc.color.GetRandomColorResp
	3, // 3: rpc.color.ColorService.GetRGBColor:output_type -> rpc.color.GetRGBColorResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_color_service_service_proto_init() }
func file_protos_color_service_service_proto_init() {
	if File_protos_color_service_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_color_service_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_color_service_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomColorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_color_service_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRGBColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_color_service_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRGBColorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_color_service_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_color_service_service_proto_goTypes,
		DependencyIndexes: file_protos_color_service_service_proto_depIdxs,
		MessageInfos:      file_protos_color_service_service_proto_msgTypes,
	}.Build()
	File_protos_color_service_service_proto = out.File
	file_protos_color_service_service_proto_rawDesc = nil
	file_protos_color_service_service_proto_goTypes = nil
	file_protos_color_service_service_proto_depIdxs = nil
}
